### PR TITLE
Removes Bower

### PR DESCRIPTION
**Pull request by paulreeve**
#### Overview

Unlike most, I develop behind a corporate proxy which makes NPM just about bearable but Bower completely out of the question. Having inspected what libraries Bower was being used for, I realised NPM could fulfil all of these. This PR removes Bower from the equation completely which obviously helps me :smile: but also should simplify things slightly.
#### Details
- Bower dependencies now fulfilled with npm.
- Dev demo now runs from `app/build` instead of `app/src`. I'm not sure if this was meant to run from `app/src` but please let me know and I can put back. `app/build` seems to make more sense.
- Some JSCS violations fixed.
#### Tests?

All unit tests run and pass in Phantom and browsers:

``` shell
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket fwFKhGTNB3hshgt-WldZ with id 50528167
..............................
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 30 of 30 SUCCESS (0.029 secs / 0.049 secs)

..............................
Chrome 46.0.2490 (Mac OS X 10.7.5): Executed 30 of 30 SUCCESS (0.132 secs / 0.119 secs)
INFO [Firefox 13.0.0 (Mac OS X 10.7.0)]: Connected on socket htFpZITc4Nchg53BWtrs with id 5745251

..............................
Firefox 13.0.0 (Mac OS X 10.7.0): Executed 30 of 30 SUCCESS (0.109 secs / 0.098 secs)
TOTAL: 60 SUCCESS
```

### CODE REVIEW

**Comment by nabil-boag** [comment]
This looks good. Thanks for the PR.

**Comment by nabil-boag** [comment]
Merging this PR I realise we don't really need a lot of the dependencies we have so I removed them here:

https://github.com/wongatech/angular-multimocks/pull/32

**Comment by paulreeve** [comment]
Awesome. Thanks @nabil-boag

**Comment by nabil-boag** [comment]
@paulreeve I just realised that the README.md needs to be updated from your PR. It still mentions bower and bower_components.

**Comment by paulreeve** [comment]
ok i'll take a look.

**Pull request merged**
