### PR TITLE
Remove ui.router dependency and update docs

### PR DESCRIPTION
**Pull request by edconolly**

### CODE REVIEW

**Comment by chrisiconolly** [comment]
Thanks for the update.
Merging in.

**Comment by nabil-boag** [comment]
I :heart: removing dependencies.

**Comment by edconolly** [comment]
Just noticed that `grunt package` is not outputting the files correctly and is instead just deleting the packaged files. Please don't merge at the minute.

**Comment by edconolly** [comment]
I've now added the proper packages - could you please merge if happy, we're dependant on `ui.router` being removed :)

**Comment by chrisiconolly** [comment]
just need to bump bower version, then looks good - and package.json

**Pull request merged**
